// Ryujin OS — Inspections (Generate Reports from Project Photos)
// GET    /api/inspections?project_id=X  — List inspections for a project
// GET    /api/inspections?id=X          — Get single inspection with details
// GET    /api/inspections?share=TOKEN   — Public view of shared inspection
// POST   /api/inspections               — Create inspection (select photos, add sections)
// PUT    /api/inspections               — Update inspection (edit sections, finalize, share)
import { supabaseAdmin } from '../lib/supabase.js';
import { requireTenant } from '../lib/tenant.js';

// Generate branded HTML for the inspection report
function generateInspectionHTML(inspection, files, tenant) {
  const branding = tenant.branding || {};
  const primaryColor = branding.colors?.primary || '#111';
  const accentColor = branding.colors?.accent || '#00ff44';
  const companyName = tenant.name;
  const phone = branding.phone || '';
  const email = branding.email || '';
  const website = branding.website || '';
  const logo = branding.logo_url || '';

  const sections = inspection.sections || [];

  const sectionHTML = sections.map((section, i) => {
    const sectionFiles = (section.file_ids || [])
      .map(fid => files.find(f => f.id === fid))
      .filter(Boolean);

    const photosHTML = sectionFiles.map(f => `
      <div class="photo-card">
        <img src="${f.annotated_url || f.url}" alt="${f.caption || ''}" />
        ${f.caption ? `<div class="photo-caption">${f.caption}</div>` : ''}
      </div>
    `).join('');

    return `
      <div class="section">
        <h2>${section.title || `Section ${i + 1}`}</h2>
        ${section.description ? `<p class="section-desc">${section.description}</p>` : ''}
        <div class="photo-grid">${photosHTML}</div>
      </div>
    `;
  }).join('');

  return `<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>${inspection.title} — ${companyName}</title>
<style>
*{margin:0;padding:0;box-sizing:border-box}
body{font-family:'Segoe UI',system-ui,sans-serif;background:#fff;color:#222;line-height:1.6}
.header{background:${primaryColor};color:#fff;padding:40px 32px;display:flex;align-items:center;gap:20px}
.header img{height:50px;border-radius:4px}
.header h1{font-size:1.4em;font-weight:700}
.header .company{font-size:0.85em;opacity:0.7}
.meta{padding:24px 32px;background:#f8f8f8;border-bottom:1px solid #eee;display:flex;gap:40px;flex-wrap:wrap;font-size:0.9em;color:#666}
.meta strong{color:#333}
.summary{padding:32px;font-size:1.05em;border-bottom:1px solid #eee}
.section{padding:32px}
.section h2{font-size:1.2em;font-weight:700;margin-bottom:8px;color:${primaryColor};border-bottom:2px solid ${accentColor};padding-bottom:6px;display:inline-block}
.section-desc{margin:12px 0 20px;color:#555}
.photo-grid{display:grid;grid-template-columns:repeat(auto-fill,minmax(280px,1fr));gap:16px;margin-top:16px}
.photo-card{border:1px solid #eee;border-radius:8px;overflow:hidden}
.photo-card img{width:100%;display:block}
.photo-caption{padding:10px 12px;font-size:0.85em;color:#555;background:#fafafa}
.footer{padding:32px;text-align:center;border-top:1px solid #eee;font-size:0.8em;color:#999;margin-top:40px}
.footer a{color:#666;text-decoration:none}
@media print{.header{-webkit-print-color-adjust:exact;print-color-adjust:exact}}
@media(max-width:600px){.photo-grid{grid-template-columns:1fr}.meta{flex-direction:column;gap:8px}}
</style>
</head>
<body>
<div class="header">
  ${logo ? `<img src="${logo}" alt="${companyName}">` : ''}
  <div>
    <h1>${inspection.title}</h1>
    <div class="company">${companyName}</div>
  </div>
</div>
<div class="meta">
  <div><strong>Date:</strong> ${new Date(inspection.created_at).toLocaleDateString('en-CA', { year: 'numeric', month: 'long', day: 'numeric' })}</div>
  <div><strong>Status:</strong> ${inspection.status.charAt(0).toUpperCase() + inspection.status.slice(1)}</div>
  <div><strong>Photos:</strong> ${(inspection.selected_files || []).length}</div>
</div>
${inspection.summary ? `<div class="summary">${inspection.summary}</div>` : ''}
${sectionHTML}
<div class="footer">
  ${companyName}${phone ? ` &middot; ${phone}` : ''}${email ? ` &middot; <a href="mailto:${email}">${email}</a>` : ''}${website ? ` &middot; <a href="${website}">${website}</a>` : ''}
  <br>Generated by Ryujin OS
</div>
</body>
</html>`;
}

async function handler(req, res) {
  if (req.method === 'OPTIONS') return res.status(200).end();

  // Public share view
  if (req.query.share) {
    const { data: inspection, error } = await supabaseAdmin
      .from('inspections')
      .select('*, tenant:tenants(name, branding)')
      .eq('share_token', req.query.share)
      .eq('shared_with_client', true)
      .single();

    if (error || !inspection) return res.status(404).json({ error: 'Inspection not found' });

    // Fetch the selected files
    const fileIds = inspection.selected_files || [];
    const { data: files } = fileIds.length > 0
      ? await supabaseAdmin.from('project_files').select('*').in('id', fileIds)
      : { data: [] };

    if (req.query.format === 'html') {
      const html = generateInspectionHTML(inspection, files || [], inspection.tenant);
      res.setHeader('Content-Type', 'text/html; charset=utf-8');
      return res.send(html);
    }

    return res.json({ inspection, files });
  }

  // Tenant-authenticated routes
  const { resolveTenant: rt } = await import('../lib/tenant.js');
  const tenant = await rt(req);
  if (!tenant) return res.status(400).json({ error: 'Tenant required' });
  const tenantId = tenant.id;

  // ── GET ──
  if (req.method === 'GET') {
    const { id, project_id } = req.query;

    if (id) {
      const { data, error } = await supabaseAdmin
        .from('inspections')
        .select('*')
        .eq('id', id)
        .eq('tenant_id', tenantId)
        .single();

      if (error) return res.status(404).json({ error: 'Inspection not found' });

      // Fetch selected files
      const fileIds = data.selected_files || [];
      const { data: files } = fileIds.length > 0
        ? await supabaseAdmin.from('project_files').select('*').in('id', fileIds)
        : { data: [] };

      return res.json({ ...data, files });
    }

    if (project_id) {
      const { data, error } = await supabaseAdmin
        .from('inspections')
        .select('id, title, status, pdf_url, shared_with_client, created_at')
        .eq('tenant_id', tenantId)
        .eq('project_id', project_id)
        .order('created_at', { ascending: false });

      if (error) return res.status(500).json({ error: error.message });
      return res.json({ inspections: data });
    }

    return res.status(400).json({ error: 'id or project_id required' });
  }

  // ── POST ──
  if (req.method === 'POST') {
    const body = req.body || {};
    if (!body.project_id) return res.status(400).json({ error: 'project_id required' });

    const shareToken = `${tenant.slug}-insp-${Date.now().toString(36)}`;

    // Generate HTML
    const { data: tenantData } = await supabaseAdmin
      .from('tenants').select('name, branding').eq('id', tenantId).single();

    const fileIds = body.selected_files || [];
    const { data: files } = fileIds.length > 0
      ? await supabaseAdmin.from('project_files').select('*').in('id', fileIds)
      : { data: [] };

    const inspectionData = {
      tenant_id: tenantId,
      project_id: body.project_id,
      created_by: body.created_by || null,
      title: body.title || 'Inspection Report',
      template: body.template || 'standard',
      summary: body.summary || null,
      selected_files: fileIds,
      sections: body.sections || [],
      status: body.status || 'draft',
      shared_with_client: body.shared_with_client || false,
      share_token: shareToken
    };

    // Generate and cache HTML
    inspectionData.html_content = generateInspectionHTML(
      { ...inspectionData, created_at: new Date().toISOString() },
      files || [],
      tenantData
    );

    const { data, error } = await supabaseAdmin
      .from('inspections')
      .insert(inspectionData)
      .select('*')
      .single();

    if (error) return res.status(500).json({ error: error.message });

    return res.status(201).json({
      ...data,
      viewUrl: `/api/inspections?share=${shareToken}&format=html`
    });
  }

  // ── PUT ──
  if (req.method === 'PUT') {
    const { id, ...updates } = req.body || {};
    if (!id) return res.status(400).json({ error: 'Missing id' });

    // If sections or files changed, regenerate HTML
    if (updates.sections || updates.selected_files || updates.summary) {
      const { data: existing } = await supabaseAdmin
        .from('inspections').select('*').eq('id', id).eq('tenant_id', tenantId).single();
      const { data: tenantData } = await supabaseAdmin
        .from('tenants').select('name, branding').eq('id', tenantId).single();

      const merged = { ...existing, ...updates };
      const fileIds = merged.selected_files || [];
      const { data: files } = fileIds.length > 0
        ? await supabaseAdmin.from('project_files').select('*').in('id', fileIds)
        : { data: [] };

      updates.html_content = generateInspectionHTML(merged, files || [], tenantData);
    }

    const { data, error } = await supabaseAdmin
      .from('inspections')
      .update(updates)
      .eq('id', id)
      .eq('tenant_id', tenantId)
      .select('*')
      .single();

    if (error) return res.status(500).json({ error: error.message });
    return res.json(data);
  }

  return res.status(405).json({ error: 'Method not allowed' });
}

export default handler;
